import { AlertTriangle, CheckCircle2, CircleDashed, LockKeyhole, Sparkles } from "lucide-react";
import { Topbar } from "@/components/topbar";
import { demoKubernetesGraph } from "@explainara/knowledge";
import { demoTwin } from "@/lib/demo";

const positions=[[70,70],[310,70],[310,245],[550,155],[550,350],[760,350]];
export default function KnowledgePage(){
  const twin=demoTwin();
  return <><Topbar title="Knowledge map" eyebrow="Concept intelligence"/><div className="knowledge-layout"><div className="card graph-canvas"><div className="graph-stage">
    <svg width="900" height="620" style={{position:"absolute",inset:0,pointerEvents:"none"}}>{demoKubernetesGraph.edges.map((e,i)=>{const a=demoKubernetesGraph.nodes.findIndex(n=>n.id===e.from),b=demoKubernetesGraph.nodes.findIndex(n=>n.id===e.to); const p1=positions[a]!,p2=positions[b]!; return <line key={i} x1={p1[0]+190} y1={p1[1]+45} x2={p2[0]} y2={p2[1]+45} stroke="#cfd3df" strokeWidth="2"/>})}</svg>
    {demoKubernetesGraph.nodes.map((n,i)=>{const m=Math.round((twin.concepts[n.id]?.mastery??0)*100); const hasMis=twin.concepts[n.id]?.misconceptions.some(x=>!x.resolved); const [x,y]=positions[i]!; const state=m>=80?"mastered":m>=45?"learning":m>0?"weak":"locked"; return <div className="graph-node" key={n.id} style={{left:x,top:y}}><div style={{fontSize:11,fontWeight:800,textTransform:"uppercase",letterSpacing:".06em",color:hasMis?"#b44b4b":"#7a7f8b"}}><span className="state" style={{background:hasMis?"#d65353":state==="mastered"?"#12a66a":state==="learning"?"#d38a13":"#aeb3bf"}}/>{hasMis?"misconception":state}</div><strong style={{display:"block",fontSize:14,margin:"7px 0"}}>{n.title}</strong><div className="progress"><span style={{width:`${m}%`}}/></div><div style={{display:"flex",justifyContent:"space-between",fontSize:11,marginTop:7}}><span className="muted">Mastery</span><b>{m}%</b></div></div>})}
  </div></div><aside className="card"><div className="eyebrow">Selected insight</div><h2 style={{marginTop:9}}>NAT and Routing</h2><p className="muted" style={{fontSize:13}}>This concept is currently blocking Kubernetes Pod Networking.</p><div className="callout"><AlertTriangle size={16} style={{verticalAlign:-3,marginRight:6}}/>High-confidence misconception detected: NAT modifies application payload.</div><div className="section-head" style={{marginBottom:9}}><h3>Mastery dimensions</h3></div>{[["Recall",69],["Understanding",58],["Application",44],["Explanation",52],["Problem solving",46]].map(([l,v])=><div key={l as string} style={{marginBottom:12}}><div style={{display:"flex",justifyContent:"space-between",fontSize:12,marginBottom:5}}><span>{l}</span><b>{v}%</b></div><div className="progress"><span style={{width:`${v}%`}}/></div></div>)}<div className="section-head" style={{marginBottom:8}}><h3>Recommended next</h3></div><button className="button brand" style={{width:"100%"}}><Sparkles size={15}/>Packet-routing simulation</button></aside></div></>;
}
